# This is a basic workflow to help you get started with Actions

name: Build and push to site

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Setup Node.js environment
              uses: actions/setup-node@v2.5.1
              with:
                  node-version: 16.x
            - name: install yarn
              run: npm i -g yarn
            - name: run yarn
              run: yarn
            - name: build release
              run: yarn build
            - name: create distribution
              run: node ./tools/distribute.js ${{ github.ref_name }}
              env:
                  API_KEY: ${{ deploy.secrets.API_KEY }}
                  APP_ID: ${{ deploy.secrets.SECRET_KEY }}
                  AUTH_DOMAIN: ${{ deploy.secrets.AUTH_DOMAIN }}
                  MEASUREMENT_ID: ${{ deploy.secrets.MEASUREMENT_ID }}
                  MESSAGE_SENDER_ID: ${{ deploy.secrets.MESSAGE_SENDER_ID }}
                  PROJECT_ID: ${{ deploy.secrets.PROJECT_ID }}
                  STORAGE_BUCKET: ${{ deploy.secrets.STORAGE_BUCKET }}
                  GITHUB_REF: ${{ deploy.github.ref_name }}
